import type { Metadata } from "next";
import { jakartaSans } from "./ui/fonts";
import "./globals.css";
import { ThemeProvider } from "./ui/theme-provider";
import AuthProviderWrapper from "@/components/ui/AuthProviderWrapper";
import Navbar from "./ui/navbar/navbar";
import ConditionalNavbar from "@/components/ConditionalNavbar";
import Footer from "@/components/Footer";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${jakartaSans.className}  antialiased bg-black  `}>
        <AuthProviderWrapper>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <ConditionalNavbar />
            {children}

            <Footer />
          </ThemeProvider>
        </AuthProviderWrapper>
      </body>
    </html>
  );
}
